language: php

sudo: true

services:
  - mysql
  - postgresql

php:
 - 7.0
 - 7.1

env:
 global:
  - MOODLE_BRANCH=MOODLE_35_STABLE
  - MOODLE_BRANCH=MOODLE_36_STABLE
  - MOODLE_BRANCH=MOODLE_37_STABLE
  - MOODLE_BRANCH=MOODLE_38_STABLE
 matrix:
  - DB=pgsql
  - DB=mysqli
